### ISSUE TITLE
注解路由未生效

### ISSUE THREAD

**Issue by caoyanbin1993** [xxjwxc/ginrpc#2]
查看[mode]/routers中有文件gen_routers.go，但未根据注解生成路由
![image](https://user-images.githubusercontent.com/20960032/74666245-21cd9e80-51dc-11ea-9280-1b64997b9847.png)

**Comment by xxjwxc** [comment]
能给我你的demo,或者你的代码吗？

**Comment by caoyanbin1993** [comment]
`package main

import (
	"fmt"
	"net/http"

	// _ "ginweb/routers" // Debug mode requires adding [mod] / routes to register annotation routes.debug模式需要添加[mod]/routers 注册注解路由

	"github.com/gin-gonic/gin"
	"github.com/xxjwxc/ginrpc"
	"github.com/xxjwxc/ginrpc/api"
)

type ReqTest struct {
	Access_token string `json:"access_token"`
	UserName     string `json:"user_name" binding:"required"` // With verification mode
	Password     string `json:"password"`
}

// Hello ...
type Hello struct {
}

// Hello Annotated route (bese on beego way)
// @router /block [post,get]
func (s *Hello) Hello(c *api.Context, req *ReqTest) {
	fmt.Println(req)
	c.JSON(http.StatusOK, "ok")
}

// Hello2 Route without annotation (the parameter is 2 default post)
func (s *Hello) Hello2(c *gin.Context, req ReqTest) {
	fmt.Println(req)
	c.JSON(http.StatusOK, "ok")
}

// [grpc-go](https://github.com/grpc/grpc-go)
// with request,return parameter and error
// Hello3 Route without annotation (the parameter is 2 default post)
func (s *Hello) Hello3(c *gin.Context, req ReqTest) (*ReqTest, error) {
	fmt.Println(req)
	return &req, nil
}

func main() {
	base := ginrpc.New(ginrpc.WithCtx(func(c *gin.Context) interface{} {
		return api.NewCtx(c)
	}), ginrpc.WithDebug(true), ginrpc.WithGroup("xxjwxc"))

	router := gin.Default()
	base.Register(router, new(Hello)) // object register like(go-micro)
	// or base.Register(router, new(Hello))
	router.Run(":8080")
}
`

**Comment by xxjwxc** [comment]
我猜测你没有在main.go中添加

_ "[mod]/routers" 

import导入

参考demo

https://github.com/xxjwxc/ginrpc.git

**Comment by caoyanbin1993** [comment]
完全用的你的案例，主要是：gen_router.go只有这样？但我代码中确实用了：// @router /block [post,get]怀疑是路由解析？
![image](https://user-images.githubusercontent.com/20960032/74667969-3f503780-51df-11ea-9cc4-dc36e6c7b191.png)


```
package main

import (
	"fmt"
	"net/http"

	// _ "ginweb/routers" // Debug mode requires adding [mod] / routes to register annotation routes.debug模式需要添加[mod]/routers 注册注解路由

	"github.com/gin-gonic/gin"
	"github.com/xxjwxc/ginrpc"
	"github.com/xxjwxc/ginrpc/api"
)

type ReqTest struct {
	Access_token string `json:"access_token"`
	UserName     string `json:"user_name" binding:"required"` // With verification mode
	Password     string `json:"password"`
}

// Hello ...
type Hello struct {
}

// Hello Annotated route (bese on beego way)
// @router /block [post,get]
func (s *Hello) Hello(c *api.Context, req *ReqTest) {
	fmt.Println(req)
	c.JSON(http.StatusOK, "ok")
}

// Hello2 Route without annotation (the parameter is 2 default post)
func (s *Hello) Hello2(c *gin.Context, req ReqTest) {
	fmt.Println(req)
	c.JSON(http.StatusOK, "ok")
}

// [grpc-go](https://github.com/grpc/grpc-go)
// with request,return parameter and error
// Hello3 Route without annotation (the parameter is 2 default post)
func (s *Hello) Hello3(c *gin.Context, req ReqTest) (*ReqTest, error) {
	fmt.Println(req)
	return &req, nil
}

func main() {
	base := ginrpc.New(ginrpc.WithCtx(func(c *gin.Context) interface{} {
		return api.NewCtx(c)
	}), ginrpc.WithDebug(true), ginrpc.WithGroup("xxjwxc"))

	router := gin.Default()
	base.Register(router, new(Hello)) // object register like(go-micro)
	// or base.Register(router, new(Hello))
	router.Run(":8080")
}

```

**Comment by xxjwxc** [comment]
你把
// _ "ginweb/routers" 
这个注释打开试下

**Comment by xxjwxc** [comment]
运行的时候报什么错误？

**Comment by xxjwxc** [comment]
你有微信或者qq不？我想远程帮你看下

**Comment by caoyanbin1993** [comment]
1278154346

**Comment by caoyanbin1993** [comment]
感谢大神！QQ:  1278154346

**Comment by xxjwxc** [comment]
已修复。

**Comment by caoyanbin1993** [comment]
已解决，感谢大神。
