### ISSUE TITLE
自动参数绑定，传参错误时，解析报错

### ISSUE THREAD

**Issue by caoyanbin1993** [xxjwxc/ginrpc#4]
针对自动参数绑定示例，将结构体改为：
```
type ReqTest struct {
	Access_token string `json:"access_token"`
	UserName     string `json:"user_name" binding:"required"` // With verification mode.带校验方式
	Password     int `json:"password"`
}
```

```curl 'http://127.0.0.1:8080/xxjwxc/block' -H 'Content-Type: application/json' -d '{"access_token":"111", "user_name":"222", "password":333}'```
正常，执行
```curl 'http://127.0.0.1:8080/xxjwxc/block' -H 'Content-Type: application/json' -d '{"access_token":"111", "user_name":"222", "password":"333"}'```
报错

自动参数绑定无法将字符串类型转换为int类型，建议做个兼容
int 2 string
string 2 int

**Comment by caoyanbin1993** [comment]
此外还有一个问题，用了ginrpc后，gin无法捕获rpc中的panic

**Comment by caoyanbin1993** [comment]
还有，自动解析建议兼容get请求

**Comment by xxjwxc** [comment]
> 此外还有一个问题，用了 ginrpc 后，gin 无法捕获 rpc 中的 panic
已修复

**Comment by xxjwxc** [comment]
> 还有，自动解析建议兼容 get 请求

请使用：form 表单标签

参考链接：
https://gin-gonic.com/zh-cn/docs/examples/binding-and-validation/

**Comment by caoyanbin1993** [comment]
需要在tag中增加form标签：
```
Page    int    `form:"page" json:"page" xml:"page"`
```
